services:
  frontend:
    build: ./frontend/setup
    volumes:
      - ./frontend/setup:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - flashcards_network
    command: npm run dev

  # backend:
  #   build:
  #     context: ./backend
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8000:5000"
  #   command: flask run --host=0.0.0.0 --port=5000 --reload
  #   networks:
  #     - flashcards_network
  #   depends_on:
  #     - db

  # db:
  #   image: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: flashcards
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - flashcards_db:/var/lib/mysql
  #   networks:
  #     - flashcards_network

# volumes:
#   flashcards_frontend:
  # flashcards_backend:
  # flashcards_db:

networks:
  flashcards_network:
    driver: bridge